[tool.poetry]
name = "test-lambda"
version = "0.1.0"
description = ""
authors = ["Taofeek <akanniboelajie.taofeek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
